---
- name: Install Nginx (Debian-based)
  apt:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"

- name: Install Nginx (RedHat-based)
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure Nginx service is enabled and started
  service:
    name: nginx
    state: started
    enabled: yes
  tags: service

- name: Ensure Nginx sites-available directory exists
  file:
    path: /etc/nginx/sites-available
    state: directory
    mode: '0755'

- name: Deploy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
  notify: Restart Nginx
  tags: config
