galaxy_info:
  author: Kumsa Mergia
  description: mastering Ansible
  company: FIGURING OUT
  license: MIT
  min_ansible_version: 2.1

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - nginx
    - web
    - server

  dependencies: []
